# Limpieza y ingeniería de atributos
Este notebook va a ser para limpiar el dataframe.

Se recibe como entrada un dataframe (puede ser el de cualquier año o el consolidado total) y se van a procesar y limpiar las siguientes columnas:

- Género: Poner únicamente los géneros en F, M, No especificado
- Edad: Verificar que no haya edades negativas o que no cuadren (muy bajas o muy altas)
- Fechas: Verificar que estén en formato DD/MM/AAAA
- Eliminar nulos y duplicados

# Bibliotecas

In [18]:
%pip install polars

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: polars in c:\users\deiss\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.32.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\deiss\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [19]:
import polars as pl
import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import re
from collections import Counter

# Obtenemos los datos de entrada

In [20]:
df = pl.read_parquet("DATA/consolidado_2010.parquet")
df

shape: (841_079, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ str       ┆ str       ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ F          ┆ 29         ┆ 84   ┆ 70         ┆ … ┆ 26         ┆ 2010-10-0 ┆ 00:28:47. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 243000    ┆ sv        │
│ M          ┆ 35         ┆ 1129 ┆ 25         ┆ … ┆ 36         ┆ 2010-10-0 ┆ 00:21:07. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 183000    ┆ sv        │
│ M          ┆ 25         ┆ 1086 ┆ 7          ┆ … ┆ 80         ┆ 2010-10-0 ┆ 00:27:12. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 363000    ┆ sv        │
│ M          ┆ 28         ┆ 1184 ┆ 77         ┆ … ┆ 65         ┆ 2010-10-0 ┆ 00:33:18. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 540000    ┆ sv        │
│ M          ┆ 41         ┆ 1120 ┆ 25         ┆ … ┆ 36         ┆ 2010-10-0 ┆ 00:20:53. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 870000    ┆ sv        │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ M          ┆ 39         ┆ 641  ┆ 26         ┆ … ┆ 22         ┆ 2010-09-3 ┆ 00:10:01. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆ 783000    ┆ v         │
│ M          ┆ 29         ┆ 450  ┆ 68         ┆ … ┆ 59         ┆ 2010-09-3 ┆ 00:01:20. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆ 203000    ┆ v         │
│ M          ┆ 33         ┆ 659  ┆ 82         ┆ … ┆ 36         ┆ 2010-09-3 ┆ 00:00:55. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆ 703000    ┆ v         │
│ F          ┆ 34         ┆ 181  ┆ 68         ┆ … ┆ 59         ┆ 2010-09-3 ┆ 00:01:04. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆ 920000    ┆ v         │
│ M          ┆ 26         ┆ 525  ┆ 80         ┆ … ┆ 69         ┆ 2010-09-3 ┆ 00:00:36. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆ 297000    ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

# Eliminamos nulos y duplicados

In [21]:
# Verificar cuántos nulos hay
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [22]:
# Rellenar con "No especificado" todos los nulos existentes
df = df.fill_null("No especificado")

In [23]:
# Verificamos que ya no haya nulos
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [24]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

In [25]:
#Para eliminar duplicados
df.unique()

shape: (841_079, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ str       ┆ str       ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 25         ┆ 846  ┆ 23         ┆ … ┆ 23         ┆ 2010-11-0 ┆ 13:12:10. ┆ 2010/11.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 3         ┆ 887000    ┆ sv        │
│ M          ┆ 27         ┆ 1132 ┆ 13         ┆ … ┆ 20         ┆ 2010-11-0 ┆ 18:58:52. ┆ 2010/11.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 4         ┆ 990000    ┆ sv        │
│ M          ┆ 28         ┆ 1097 ┆ 36         ┆ … ┆ 74         ┆ 2010-04-2 ┆ 19:47:27. ┆ 2010/4.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 9         ┆ 323000    ┆ v         │
│ M          ┆ 60         ┆ 783  ┆ 44         ┆ … ┆ 73         ┆ 2010-05-1 ┆ 21:21:22. ┆ 2010/5.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 4         ┆ 083000    ┆ v         │
│ F          ┆ 52         ┆ 211  ┆ 55         ┆ … ┆ 41         ┆ 2010-12-0 ┆ 19:04:16. ┆ 2010/12.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 4         ┆ 637000    ┆ sv        │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ F          ┆ 34         ┆ 798  ┆ 13         ┆ … ┆ 22         ┆ 2010-04-2 ┆ 10:25:21. ┆ 2010/4.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆ 273000    ┆ v         │
│ M          ┆ 42         ┆ 497  ┆ 34         ┆ … ┆ 28         ┆ 2010-08-0 ┆ 11:37:36. ┆ 2010/8.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 5         ┆ 803000    ┆ v         │
│ F          ┆ 52         ┆ 742  ┆ 69         ┆ … ┆ 53         ┆ 2010-10-2 ┆ 19:40:23. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 7         ┆ 887000    ┆ sv        │
│ M          ┆ 47         ┆ 1005 ┆ 25         ┆ … ┆ 7          ┆ 2010-06-2 ┆ 20:29:35. ┆ 2010/6.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 8         ┆ 090000    ┆ v         │
│ M          ┆ 30         ┆ 137  ┆ 29         ┆ … ┆ 34         ┆ 2010-06-1 ┆ 18:57:06. ┆ 2010/6.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆ 257000    ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [26]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

# Tratamiento a columna "Genero_Usuario"
Solo vamos a tomar en cuenta los registros que sean 'F', 'M' y 'No especificado'. Los registros que no sean 'F' o 'M', serán reemplazados por 'No especificado'.

Estos registros ya son conocidos, son los valores: 'O', '?' y 'nan'

In [27]:
valores_no_estandar = ['O', '?', 'nan'] 
df = df.with_columns(
    pl.col("Genero_Usuario").replace(valores_no_estandar, 'No especificado')
)

print("\nValores de 'Genero_Usuario' después de la limpieza:")
print(df['Genero_Usuario'].value_counts())

Valores de 'Genero_Usuario' después de la limpieza:
shape: (2, 2)
┌────────────────┬────────┐
│ Genero_Usuario ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ M              ┆ 615408 │
│ F              ┆ 225671 │
└────────────────┴────────┘

# Tratamiento a columnas de fechas

In [28]:
#Revisar si podemos estandarizar los años con horas extrañas, sino, solo trabajamos desde 2017
df = df.with_columns(
    pl.col("Fecha_Retiro")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False),

    pl.col("Fecha_Arribo")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False)
)

print("2010 procesado correctamente")

2010 procesado correctamente

In [29]:
#Revisar si podemos estandarizar los años con horas extrañas, sino, solo trabajamos desde 2017
def fix_time(col):
    return (
        pl.col(col)
        # Si falta microsegundos: agregar ".000000"
        .str.replace_all(r"^(\d{1,2}:\d{2}:\d{2})$", r"\1.000000")
        # Si la hora tiene un solo dígito al inicio: anteponer "0"
        .str.replace_all(r"^(\d:)", r"0\1")
        # Convertir a time
        .str.strptime(pl.Time, format="%H:%M:%S%.f", strict=False)
    )

df = df.with_columns(
    [
        fix_time("Hora_Retiro").alias("Hora_Retiro"),
        fix_time("Hora_Arribo").alias("Hora_Arribo"),
    ]
)

df

shape: (841_079, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ date      ┆ time      ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ F          ┆ 29         ┆ 84   ┆ 70         ┆ … ┆ 26         ┆ null      ┆ 00:28:47. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 243       ┆ sv        │
│ M          ┆ 35         ┆ 1129 ┆ 25         ┆ … ┆ 36         ┆ null      ┆ 00:21:07. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 183       ┆ sv        │
│ M          ┆ 25         ┆ 1086 ┆ 7          ┆ … ┆ 80         ┆ null      ┆ 00:27:12. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 363       ┆ sv        │
│ M          ┆ 28         ┆ 1184 ┆ 77         ┆ … ┆ 65         ┆ null      ┆ 00:33:18. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 540       ┆ sv        │
│ M          ┆ 41         ┆ 1120 ┆ 25         ┆ … ┆ 36         ┆ null      ┆ 00:20:53. ┆ 2010/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 870       ┆ sv        │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ M          ┆ 39         ┆ 641  ┆ 26         ┆ … ┆ 22         ┆ null      ┆ 00:10:01. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 783       ┆ v         │
│ M          ┆ 29         ┆ 450  ┆ 68         ┆ … ┆ 59         ┆ null      ┆ 00:01:20. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 203       ┆ v         │
│ M          ┆ 33         ┆ 659  ┆ 82         ┆ … ┆ 36         ┆ null      ┆ 00:00:55. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 703       ┆ v         │
│ F          ┆ 34         ┆ 181  ┆ 68         ┆ … ┆ 59         ┆ null      ┆ 00:01:04. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 920       ┆ v         │
│ M          ┆ 26         ┆ 525  ┆ 80         ┆ … ┆ 69         ┆ null      ┆ 00:00:36. ┆ 2010/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 297       ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [31]:
# =============================================================================
#    CONFIGURACIÓN INICIAL Y ANÁLISIS EXPLORATORIO
# =============================================================================

print("=== ANÁLISIS INICIAL DE EDAD_USUARIO ===")

# Primero convertimos a string y limpiamos espacios
df = df.with_columns([
    pl.col("Edad_Usuario")
    .cast(pl.Utf8)
    .str.strip_chars()  # Limpiamos espacios en blanco
    .alias("Edad_Usuario")
])

# Estadísticas iniciales de la columna
print(f"Total de registros: {len(df):,}")
print(f"Valores nulos: {df['Edad_Usuario'].null_count()}")
print(f"Valores únicos: {df['Edad_Usuario'].n_unique()}")

# Mostrar algunos valores únicos para verificar formato
print(f"\nPrimeros 10 valores únicos: {df['Edad_Usuario'].unique()[:10].to_list()}")

=== ANÁLISIS INICIAL DE EDAD_USUARIO ===
Total de registros: 841,079
Valores nulos: 0
Valores únicos: 65

Primeros 10 valores únicos: ['79', '61', '42', '19', '63', '22', '76', '69', '31', '67']

In [32]:
# =============================================================================
# CONVERSIÓN A NUMÉRICO Y DETECCIÓN DE OUTLIERS
# =============================================================================

# Convertir a numérico (manejando errores de conversión)
df = df.with_columns([
    pl.col("Edad_Usuario")
    .cast(pl.Int64, strict=False)  # strict=False permite manejar valores no convertibles
    .alias("Edad_Usuario_Numeric")
])

print("=== ANÁLISIS DE VALORES ATÍPICOS ===")
print(f"Valores nulos después de conversión: {df['Edad_Usuario_Numeric'].null_count()}")

# Contar outliers según criterios establecidos (menores de 16, mayores de 70)
menores_16 = df.filter(pl.col("Edad_Usuario_Numeric") < 16).height
mayores_70 = df.filter(pl.col("Edad_Usuario_Numeric") > 70).height
nulos = df['Edad_Usuario_Numeric'].null_count()

print(f"Edades menores de 16 años: {menores_16:,}")
print(f"Edades mayores de 70 años: {mayores_70:,}")
print(f"Valores nulos: {nulos:,}")
print(f"Total de outliers a tratar: {menores_16 + mayores_70 + nulos:,}")

=== ANÁLISIS DE VALORES ATÍPICOS ===
Valores nulos después de conversión: 0
Edades menores de 16 años: 0
Edades mayores de 70 años: 952
Valores nulos: 0
Total de outliers a tratar: 952

In [33]:
# =============================================================================
# CÁLCULO DE MEDIANA Y REEMPLAZO DE OUTLIERS
# =============================================================================

# Calcular mediana excluyendo outliers para obtener un valor representativo
edades_validas = df.filter(
    (pl.col("Edad_Usuario_Numeric") >= 16) & 
    (pl.col("Edad_Usuario_Numeric") <= 70) &
    (pl.col("Edad_Usuario_Numeric").is_not_null())
)

mediana = edades_validas.select(pl.col("Edad_Usuario_Numeric").median()).item()
print(f"Mediana calculada (solo edades 16-70 años): {mediana}")

# Reemplazar outliers y nulos con la mediana calculada
df = df.with_columns([
    pl.when(
        (pl.col("Edad_Usuario_Numeric") < 16) | 
        (pl.col("Edad_Usuario_Numeric") > 70) |
        (pl.col("Edad_Usuario_Numeric").is_null())
    )
    .then(pl.lit(int(mediana)))  # Asignar mediana a outliers
    .otherwise(pl.col("Edad_Usuario_Numeric"))  # Mantener valores válidos
    .cast(pl.Int64)  # Asegurar tipo entero
    .alias("Edad_Usuario_Limpio")  # Nueva columna limpia
])

Mediana calculada (solo edades 16-70 años): 32.0

In [34]:
# =============================================================================
# VERIFICACIÓN Y VALIDACIÓN DE RESULTADOS
# =============================================================================

print("=== VERIFICACIÓN FINAL ===")
print(f"Valores nulos después de limpieza: {df['Edad_Usuario_Limpio'].null_count()}")
print(f"Nueva edad mínima: {df['Edad_Usuario_Limpio'].min()}")
print(f"Nueva edad máxima: {df['Edad_Usuario_Limpio'].max()}")
print(f"Mediana final: {df['Edad_Usuario_Limpio'].median()}")

# Distribución completa de edades limpias
print("\n=== DISTRIBUCIÓN DE EDADES LIMPIAS ===")
print(df['Edad_Usuario_Limpio'].describe())

=== VERIFICACIÓN FINAL ===
Valores nulos después de limpieza: 0
Nueva edad mínima: 16
Nueva edad máxima: 70
Mediana final: 32.0

=== DISTRIBUCIÓN DE EDADES LIMPIAS ===
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 841079.0  │
│ null_count ┆ 0.0       │
│ mean       ┆ 34.183419 │
│ std        ┆ 9.978796  │
│ min        ┆ 16.0      │
│ 25%        ┆ 27.0      │
│ 50%        ┆ 32.0      │
│ 75%        ┆ 40.0      │
│ max        ┆ 70.0      │
└────────────┴───────────┘

In [35]:
# =============================================================================
# EJEMPLOS DE LA TRANSFORMACIÓN
# =============================================================================

# Mostrar ejemplos de antes y después para verificar la transformación
print("=== EJEMPLOS DE LIMPIEZA ===")
ejemplos = df.select([
    "Edad_Usuario", 
    "Edad_Usuario_Limpio"
]).head(10)
print(ejemplos)

print("\n ¡Limpieza completada! Columna 'Edad_Usuario_Limpio' creada con tipo Int64")
print("Sin valores nulos ni outliers")
print("Lista para análisis estadístico")

=== EJEMPLOS DE LIMPIEZA ===
shape: (10, 2)
┌──────────────┬─────────────────────┐
│ Edad_Usuario ┆ Edad_Usuario_Limpio │
│ ---          ┆ ---                 │
│ str          ┆ i64                 │
╞══════════════╪═════════════════════╡
│ 29           ┆ 29                  │
│ 35           ┆ 35                  │
│ 25           ┆ 25                  │
│ 28           ┆ 28                  │
│ 41           ┆ 41                  │
│ 30           ┆ 30                  │
│ 34           ┆ 34                  │
│ 31           ┆ 31                  │
│ 31           ┆ 31                  │
│ 47           ┆ 47                  │
└──────────────┴─────────────────────┘

 ¡Limpieza completada! Columna 'Edad_Usuario_Limpio' creada con tipo Int64
Sin valores nulos ni outliers
Lista para análisis estadístico