# Limpieza y ingeniería de atributos
Este notebook va a ser para limpiar el dataframe.

Se recibe como entrada un dataframe (puede ser el de cualquier año o el consolidado total) y se van a procesar y limpiar las siguientes columnas:

- Género: Poner únicamente los géneros en F, M, No especificado
- Edad: Verificar que no haya edades negativas o que no cuadren (muy bajas o muy altas)
- Fechas: Verificar que estén en formato DD/MM/AAAA
- Eliminar nulos y duplicados

# Bibliotecas

In [1]:
%pip install polars

Requirement already satisfied: polars in c:\users\diego\appdata\local\programs\python\python313\lib\site-packages (1.35.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in c:\users\diego\appdata\local\programs\python\python313\lib\site-packages (from polars) (1.35.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import polars as pl
import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import re
from collections import Counter

# Obtenemos los datos de entrada

In [ ]:
df = pl.read_parquet("G:/.shortcut-targets-by-id/1NDRK_eUkNH2l92aHtOZVY-QThQVb6lil/Tlamatini/DATA/consolidado_por_año/consolidado_2024.parquet")
df

shape: (22_242_869, 10)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usua ┆ Bici    ┆ Ciclo_Est ┆ … ┆ Ciclo_Est ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ rio       ┆ ---     ┆ acion_Ret ┆   ┆ acion_Arr ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---       ┆ i64     ┆ iro       ┆   ┆ ibo       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆         ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│            ┆           ┆         ┆ str       ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 48.0      ┆ 3371879 ┆ 113       ┆ … ┆ 659       ┆ 01/01/202 ┆ 00:00:02  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 26.0      ┆ 7033434 ┆ 281       ┆ … ┆ 047       ┆ 01/01/202 ┆ 00:00:02  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 37.0      ┆ 7169857 ┆ 015       ┆ … ┆ 217       ┆ 01/01/202 ┆ 00:00:49  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 30.0      ┆ 6368211 ┆ 555       ┆ … ┆ 008       ┆ 01/01/202 ┆ 00:02:39  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 30.0      ┆ 5136924 ┆ 555       ┆ … ┆ 008       ┆ 01/01/202 ┆ 00:02:45  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ M          ┆ 31.0      ┆ 8088551 ┆ 425       ┆ … ┆ 371       ┆ 30/09/202 ┆ 23:59:19  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 31.0      ┆ 7701659 ┆ 107-108   ┆ … ┆ 006       ┆ 30/09/202 ┆ 23:59:23  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 23.0      ┆ 2022929 ┆ 004       ┆ … ┆ 505       ┆ 30/09/202 ┆ 23:59:37  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 62.0      ┆ 2449668 ┆ 004       ┆ … ┆ 111       ┆ 30/09/202 ┆ 23:59:44  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 32.0      ┆ 7130065 ┆ 453       ┆ … ┆ 292       ┆ 30/09/202 ┆ 23:59:48  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Eliminamos nulos y duplicados

In [145]:
# Verificar cuántos nulos hay
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 93         ┆ 662        ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [20]:
# Rellenar con "No especificado" todos los nulos existentes
df = df.fill_null("No especificado")

In [21]:
# Verificamos que ya no haya nulos
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [36]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

In [23]:
#Para eliminar duplicados
df.unique()

shape: (9_069_543, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ str       ┆ str       ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 50         ┆ 3513 ┆ 29         ┆ … ┆ 71         ┆ 2016-02-0 ┆ 13:38:00. ┆ 2016/2.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 8         ┆ 420000    ┆ v         │
│ M          ┆ 52         ┆ 1716 ┆ 168        ┆ … ┆ 182        ┆ 2016-04-1 ┆ 08:29:29  ┆ 2016/4.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆           ┆ v         │
│ M          ┆ 45         ┆ 2297 ┆ 6          ┆ … ┆ 313        ┆ 2016-05-3 ┆ 16:16:59  ┆ 2016/5.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆           ┆ v         │
│ F          ┆ 59         ┆ 4899 ┆ 187        ┆ … ┆ 187        ┆ 2016-06-2 ┆ 12:57:55  ┆ 2016/6.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1         ┆           ┆ v         │
│ M          ┆ 36         ┆ 4440 ┆ 396        ┆ … ┆ 425        ┆ 2016-01-0 ┆ 19:40:23  ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ M          ┆ 29         ┆ 1869 ┆ 43         ┆ … ┆ 26         ┆ 2016-01-0 ┆ 10:17:01  ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ M          ┆ 30         ┆ 2544 ┆ 106        ┆ … ┆ 19         ┆ 2016-05-2 ┆ 10:11:18  ┆ 2016/5.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ M          ┆ 36         ┆ 4992 ┆ 194        ┆ … ┆ 52         ┆ 2016-05-2 ┆ 14:50:13  ┆ 2016/5.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 7         ┆           ┆ v         │
│ M          ┆ 36         ┆ 4180 ┆ 295        ┆ … ┆ 317        ┆ 20/09/201 ┆ 9:37:35   ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ M          ┆ 23         ┆ 3237 ┆ 3          ┆ … ┆ 3          ┆ 2016-04-1 ┆ 19:52:28. ┆ 2016/4.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 8         ┆ 720000    ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [59]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

# Tratamiento a columna "Genero_Usuario"
Solo vamos a tomar en cuenta los registros que sean 'F', 'M' y 'No especificado'. Los registros que no sean 'F' o 'M', serán reemplazados por 'No especificado'.

Estos registros ya son conocidos, son los valores: 'O', '?' y 'nan'

In [25]:
valores_no_estandar = ['O', '?', 'nan'] 
df = df.with_columns(
    pl.col("Genero_Usuario").replace(valores_no_estandar, 'No especificado')
)

print("\nValores de 'Genero_Usuario' después de la limpieza:")
print(df['Genero_Usuario'].value_counts())

Valores de 'Genero_Usuario' después de la limpieza:
shape: (2, 2)
┌────────────────┬─────────┐
│ Genero_Usuario ┆ count   │
│ ---            ┆ ---     │
│ str            ┆ u32     │
╞════════════════╪═════════╡
│ M              ┆ 6810462 │
│ F              ┆ 2259081 │
└────────────────┴─────────┘

# Tratamiento a columnas de fechas

In [13]:
#Revisar si podemos estandarizar los años con horas extrañas, sino, solo trabajamos desde 2017
df = df.with_columns(
    pl.col("Fecha_Retiro")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False),

    pl.col("Fecha_Arribo")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False)
)

print("Procesado correctamente")

Procesado correctamente

In [26]:
# Verificamos que ya no haya nulos
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [74]:
df.select(
    pl.col("Hora_Retiro").is_null().sum().alias("Nulos_Nativos_R"),
    (pl.col("Hora_Retiro") == pl.lit("")).sum().alias("Cadenas_Vacias_R"),
    (pl.col("Hora_Retiro") == pl.lit("...")).sum().alias("Otros_Invalidos_R"),
    pl.col("Hora_Arribo").is_null().sum().alias("Nulos_Nativos_A"),
    (pl.col("Hora_Arribo") == pl.lit("")).sum().alias("Cadenas_Vacias_A"),
    (pl.col("Hora_Arribo") == pl.lit("...")).sum().alias("Otros_Invalidos_A")
)

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ Nulos_Nativos_ ┆ Cadenas_Vacias ┆ Otros_Invalido ┆ Nulos_Nativos ┆ Cadenas_Vacia ┆ Otros_Invalid │
│ R              ┆ _R             ┆ s_R            ┆ _A            ┆ s_A           ┆ os_A          │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ u32            ┆ u32            ┆ u32            ┆ u32           ┆ u32           ┆ u32           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0              ┆ 0              ┆ 0              ┆ 0             ┆ 0             ┆ 0             │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [ ]:
# Normalizador hora

def normalizar_hora(col):

    s = pl.col(col).str.strip_chars()

    # 1) Quitar microsegundos
    s = s.str.replace(r"\.\d+", "")

    # 2) Convertir AM/PM a 24h manualmente
    is_pm = s.str.contains("PM")
    is_am = s.str.contains("AM")

    # Extraer hh, mm, ss aunque tengan 1 solo dígito
    hh = s.str.extract(r"(\d+):", 1)
    mm = s.str.extract(r":(\d+):", 1)
    ss = s.str.extract(r":(\d+)\s?(AM|PM)?$", 1)

    # Convertir hh a entero
    hh_int = hh.cast(pl.Int32())

    # Reglas AM/PM
    hh_24 = (
        pl.when(is_pm & (hh_int != 12)).then(hh_int + 12)
        .when(is_pm & (hh_int == 12)).then(12)
        .when(is_am & (hh_int == 12)).then(0)
        .otherwise(hh_int)
    )

    # 3) Reconstruir HH:MM:SS con ceros
    final = (
        hh_24.cast(pl.Utf8()).str.zfill(2) + ":" +
        mm.str.zfill(2) + ":" +
        ss.str.zfill(2)
    )

    # 4) Validar como hora
    return (
        final
        .str.strptime(pl.Time, strict=False)
        .dt.strftime("%H:%M:%S")
        .alias(col)
    )

In [147]:
df = df.with_columns([
    normalizar_hora("Hora_Retiro"),
    normalizar_hora("Hora_Arribo")
])

df

shape: (22_242_869, 10)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usua ┆ Bici    ┆ Ciclo_Est ┆ … ┆ Ciclo_Est ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ rio       ┆ ---     ┆ acion_Ret ┆   ┆ acion_Arr ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---       ┆ i64     ┆ iro       ┆   ┆ ibo       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆         ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│            ┆           ┆         ┆ str       ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 48.0      ┆ 3371879 ┆ 113       ┆ … ┆ 659       ┆ 01/01/202 ┆ 00:00:02  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 26.0      ┆ 7033434 ┆ 281       ┆ … ┆ 047       ┆ 01/01/202 ┆ 00:00:02  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 37.0      ┆ 7169857 ┆ 015       ┆ … ┆ 217       ┆ 01/01/202 ┆ 00:00:49  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 30.0      ┆ 6368211 ┆ 555       ┆ … ┆ 008       ┆ 01/01/202 ┆ 00:02:39  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 30.0      ┆ 5136924 ┆ 555       ┆ … ┆ 008       ┆ 01/01/202 ┆ 00:02:45  ┆ 2024/1.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ M          ┆ 31.0      ┆ 8088551 ┆ 425       ┆ … ┆ 371       ┆ 30/09/202 ┆ 23:59:19  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 31.0      ┆ 7701659 ┆ 107-108   ┆ … ┆ 006       ┆ 30/09/202 ┆ 23:59:23  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 23.0      ┆ 2022929 ┆ 004       ┆ … ┆ 505       ┆ 30/09/202 ┆ 23:59:37  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ F          ┆ 62.0      ┆ 2449668 ┆ 004       ┆ … ┆ 111       ┆ 30/09/202 ┆ 23:59:44  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
│ M          ┆ 32.0      ┆ 7130065 ┆ 453       ┆ … ┆ 292       ┆ 30/09/202 ┆ 23:59:48  ┆ 2024/9.cs │
│            ┆           ┆         ┆           ┆   ┆           ┆ 4         ┆           ┆ v         │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [148]:
# Verificamos que ya no haya nulos
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 93         ┆ 662        ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘